### ISSUE TITLE
No action.

### ISSUE THREAD

**Issue by TheMajster** [fluidsonic/fluid-mongo#4]
Hello, i try insert some document and timeout 
code with println -> https://imgur.com/a/Qangnia

Exception ->
`Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=xxxxx:xxx, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.io.IOException: The remote computer refused the network connection
}}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:407)
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:311)
	at com.mongodb.internal.connection.BaseCluster.access$800(BaseCluster.java:62)
	at com.mongodb.internal.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:478)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by fluidsonic** [comment]
@TheMajster it means that it is not possible to create a connection to your MongoDB server.

The most likely causes are:
1. The connection string `mongodb://admin:…/admin` is invalid (wrong host or port).
2. The server is unreachable due to a firewall.
3. The server is not running.

**Comment by TheMajster** [comment]
thanks, in mongo cfg i have to change bindIp to ip vps, becouse with 127.0.0.1 doesnt working

**Comment by fluidsonic** [comment]
Happy to hear that you've solved your issue.
